### ISSUE TITLE
Using App instead of AppDelegate and SceneDelegate

### ISSUE THREAD

**Issue by dbaroncelli** [CoreyKaylor/kotlin-mpp-flow-store#1]
Hi Corey, I just wanted to suggest you can simplify the iOS app entry point, by using App:
https://twitter.com/mecid/status/1275765431907819520

**Comment by CoreyKaylor** [comment]
Yes, at the moment it's not targeting iOS 14, but when it does that change would make sense.

**Comment by CoreyKaylor** [comment]
Fixed in bcbbf2a9
